### ISSUE TITLE
fabric8 4.x seems broken - cannot login on minishift

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8-platform#1019]
the browser just responds with 
```
{"error":"invalid_request","error_description":"The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed.","state":"krFHHg9i44mvfSWAMPkHP1rTian7p3saidkDPnSlsiw.fabric8-online-platform"}
```
this seems a recent change - wonder if something in fabric8-auth has broken it? Some KeyCloak change required?

**Comment by alexeykazakov** [comment]
Any details? What endpoint returns this error? Is it 100% reproducible?

**Comment by sbose78** [comment]
I was seeing issues with `user 'developer' not approved` - to fix that I had to add the attribute mapper.

![mapper](https://user-images.githubusercontent.com/545280/31320302-17293a8c-ac90-11e7-9677-d1b7b7565c2f.png)

**Comment by rawlingsj** [comment]
All users should be approved automatically as we do this at the identity provider https://github.com/fabric8-apps/keycloak-app/blob/master/keycloak/src/main/fabric8/cm.yml#L165

@sbose78 are you saying you were able to log in on minishift after you approved the developer user?

**Comment by sbose78** [comment]
Agreed @rawlingsj  - all users are auto auto-approved. So was mine when I checked in Keycloak.

However, the token claims ( in the token issued by keycloak ) didn't have the `approved` attribute which was making the auth code feel that user is not approved. So in the above screen, I 'told keycloak' to pass the `approved` attribute in the token claims too . After that things worked again. I noticed that this 'mapper' which I've shown in the above screenshot is already there in the prod keycloak. ( @alexeykazakov , was it added by you recently ? )

Btw, the original issue in this thread was different - I checked with the reporter Suraj Narwade. He told me that this error 

`{"error":"invalid_request","error_description":"The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed.","state":"krFHHg9i44mvfSWAMPkHP1rTian7p3saidkDPnSlsiw.fabric8-online-platform"}
`

had occured when he clicked on `openshift-v3` in the keyclock login page. That looked like an oauth client setup issue in his minishift. I've asked him to start afresh and see if it could be reproduced.
I tried reproducing - but login with `openshift-v3` worked like charm for me.

**Comment by surajnarwade** [comment]
@jstrachan @sbose78 , I did,

```
oc edit oauthclient fabric8-online-platform
```
then I replaced  `redirectURIs` to this one, `http://keycloak-fabric8.192.168.42.112.nip.io/auth/realms/fabric8/broker/openshift-v3/endpoint`
and it worked :)

According to https://github.com/fabric8io/fabric8-platform/blob/master/install.sh#L56 
`redirectURIs` is not adding URL part

**Comment by jstrachan** [comment]
So I just tried it again using the [main install instructions with gofabric8](https://github.com/fabric8io/fabric8-platform/blob/master/INSTALL.md) (which used to work fine):

```
gofabric8 deploy --namespace fabric8 --package=system -y
```
the installer mentioned to make sure the github OAuth redirect URI was setup as:
```
Authorization callback URL: http://keycloak-fabric8.192.168.64.2.nip.io/auth/realms/fabric8/broker/github/endpoint
```
which I did. 

It generated an OAuthClient of:
```
NAME                           SECRET                                 WWW-CHALLENGE   REDIRECT URIS
fabric8-online-platform        fabric8                                FALSE           /auth/realms/fabric8/broker/openshift-v3/endpoint
```

I get the login button, click on the OpenShift Login button then get:
```
{
error: "invalid_request",
error_description: "The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed.",
state: "mAVeyYhev_xAwwUQXTOEnHH7wg6wg2LnHfMXp9Fpy8M.fabric8-online-platform"
}
```
with the browser at URL: https://192.168.64.2:8443/oauth/authorize?scope=user%3Afull&state=mAVeyYhev_xAwwUQXTOEnHH7wg6wg2LnHfMXp9Fpy8M.fabric8-online-platform&response_type=code&client_id=fabric8-online-platform&redirect_uri=http%3A%2F%2Fkeycloak-fabric8.192.168.64.2.nip.io%2Fauth%2Frealms%2Ffabric8%2Fbroker%2Fopenshift-v3%2Fendpoint

any ideas? I"m not using the install.sh script used above but using these instructions: https://github.com/fabric8io/fabric8-platform/blob/master/INSTALL.md

**Comment by sbose78** [comment]
I see your redirect uri for the openshift-v3 oauth client is : 
` /auth/realms/fabric8/broker/openshift-v3/endpoint`

Not thorough with the gofabric8 code , but it seems to me the that oauth client config is missing the full redirect uri - 

Is this info being used to update the redirect uri https://github.com/fabric8io/gofabric8/blob/master/cmds/deploy.go#L352 ?

**Comment by jstrachan** [comment]
aha - so it was a regression in gofabric8 https://github.com/fabric8io/gofabric8/pull/599 its working fine for me now!
